#baseURL = 'https://jaae.no/'
baseURL = 'https://joachimaae.github.io/'
languageCode = 'no'
title = 'Blogg'

[params]
title = "Joachim Aae"
author = "Joachim Aae"
description = "Bare en side for å lagre egne prosjekter og diverse"
profilePicture = "images/profile.jpg"
#displayMode = "dark"
contentratio = 0.6
#mainSections = []

  [[params.socialIcons]]
  icon = "fab fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/joachimaae/"

[menu]

  [[menu.main]]
  name = "Hovedside"
  identifier = "hovedside"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Blogg"
  weight = 200
  identifier = "blogg"
  url = "/posts/"


# theme as hugo module
#theme = "github.com/lxndrblz/anatole"
# theme as git submodule
theme = "anatole"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false


